[package]
name = "trixter"
version = "0.1.0"
authors = ["timob"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fraction = "0.6.3"
